kind: ConfigMap
apiVersion: v1
metadata:
  name: mftconfig
  namespace: enfo
data:
  command-setup.mqsc: |
    DEFINE CHANNEL('COMMAND.FTE') CHLTYPE(SVRCONN) DESCR('Command QM connection') TRPTYPE(TCP) REPLACE 
    SET CHLAUTH('COMMAND.FTE') TYPE(BLOCKUSER) DESCR('Rule to override *MQADMIN blockuser on this channel') USERLIST('nobody') ACTION(replace)
    DEFINE QLOCAL(AGENT.SOURCE) USAGE(XMITQ)
    DEFINE CHANNEL(COMMAND.AGENT.SOURCE) CHLTYPE(SDR) CONNAME('agent-source-ibm-mq(1414)') XMITQ(COORD) CONVERT(NO)
    DEFINE QLOCAL(AGENT.DEST) USAGE(XMITQ)
    DEFINE CHANNEL(COMMAND.AGENT.DEST) CHLTYPE(SDR) CONNAME('agent-dest-ibm-mq(1414)') XMITQ(COORD) CONVERT(NO)
    DEFINE CHANNEL(AGENT.SOURCE.COMMAND) CHLTYPE(RCVR)
    DEFINE CHANNEL(AGENT.DEST.COMMAND) CHLTYPE(RCVR)

  coord-setup.mqsc: |
    DEFINE CHANNEL('COORD.FTE') CHLTYPE(SVRCONN) DESCR('Coordination QM connection') TRPTYPE(TCP) REPLACE 
    SET CHLAUTH('COORD.FTE') TYPE(BLOCKUSER) DESCR('Rule to override *MQADMIN blockuser on this channel') USERLIST('nobody') ACTION(replace)
    DEFINE TOPIC('SYSTEM.FTE') TOPICSTR('SYSTEM.FTE') REPLACE
    ALTER TOPIC('SYSTEM.FTE') NPMSGDLV(ALLAVAIL) PMSGDLV(ALLAVAIL)
    DEFINE QLOCAL(SYSTEM.FTE) LIKE(SYSTEM.BROKER.DEFAULT.STREAM) REPLACE
    ALTER QLOCAL(SYSTEM.FTE) DESCR('Stream for MQMFT Pub/Sub interface')
    ALTER NAMELIST(SYSTEM.QPUBSUB.QUEUE.NAMELIST) NAMES(SYSTEM.BROKER.DEFAULT.STREAM,SYSTEM.BROKER.ADMIN.STREAM,SYSTEM.FTE)
    ALTER QMGR PSMODE(ENABLED)
    DEFINE CHANNEL(AGENT.SOURCE.COORD) CHLTYPE(RCVR)
    DEFINE CHANNEL(AGENT.DEST.COORD) CHLTYPE(RCVR)
    DEFINE CHANNEL(COMMAND.COORD) CHLTYPE(RCVR)

  agent-source-setup.mqsc: |
    DEFINE CHANNEL('AGENT.FTE') CHLTYPE(SVRCONN) DESCR('agent QM connection') TRPTYPE(TCP) REPLACE 
    SET CHLAUTH('AGENT.FTE') TYPE(BLOCKUSER) DESCR('Rule to override *MQADMINblockuser on this channel') USERLIST('nobody') ACTION(replace)
    DEFINE QLOCAL(SYSTEM.FTE.COMMAND.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(5000) MAXMSGL(4194304) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.DATA.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(5000) MAXMSGL(4194304) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.REPLY.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(5000) MAXMSGL(4194304) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.STATE.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(5000) MAXMSGL(4194304) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.EVENT.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(5000) MAXMSGL(4194304) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHAGT1.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHTRN1.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHOPS1.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHSCH1.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHMON1.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHADM1.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.HA.SOURCE) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(COORD) USAGE(XMITQ)
    DEFINE CHANNEL(AGENT.SOURCE.COORD) CHLTYPE(SDR) CONNAME('coordination-ibm-mq(1414)') XMITQ(COORD) CONVERT(NO)
    DEFINE QLOCAL(COMMAND) USAGE(XMITQ)
    DEFINE CHANNEL(AGENT.SOURCE.COMMAND) CHLTYPE(SDR) CONNAME('command-ibm-mq(1414)') XMITQ(COORD) CONVERT(NO)
    DEFINE QLOCAL(AGENT.DEST) USAGE(XMITQ)
    DEFINE CHANNEL(AGENT.SOURCE.DEST) CHLTYPE(SDR) CONNAME('agent-dest-ibm-mq(1414)') XMITQ(COORD) CONVERT(NO)
    DEFINE CHANNEL(COMMAND.AGENT.SOURCE) CHLTYPE(RCVR)    
    DEFINE CHANNEL(AGENT.DEST.SOURCE) CHLTYPE(RCVR)

  agent-dest-setup.mqsc: |
    DEFINE CHANNEL('AGENT.FTE') CHLTYPE(SVRCONN) DESCR('agent QM connection') TRPTYPE(TCP) REPLACE 
    SET CHLAUTH('AGENT.FTE') TYPE(BLOCKUSER) DESCR('Rule to override *MQADMINblockuser on this channel') USERLIST('nobody') ACTION(replace)
    DEFINE QLOCAL(SYSTEM.FTE.COMMAND.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(5000) MAXMSGL(4194304) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.DATA.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(5000) MAXMSGL(4194304) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.REPLY.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(5000) MAXMSGL(4194304) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.STATE.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(5000) MAXMSGL(4194304) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.EVENT.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(5000) MAXMSGL(4194304) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHAGT1.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHTRN1.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHOPS1.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHSCH1.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHMON1.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.AUTHADM1.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE
    DEFINE QLOCAL(SYSTEM.FTE.HA.DEST) DEFPRTY(0) DEFSOPT(SHARED) GET(ENABLED) MAXDEPTH(0) MAXMSGL(0) MSGDLVSQ(PRIORITY) PUT(ENABLED) RETINTVL(999999999) SHARE NOTRIGGER USAGE(NORMAL) REPLACE    
    DEFINE QLOCAL(COORD) USAGE(XMITQ)
    DEFINE CHANNEL(AGENT.DEST.COORD) CHLTYPE(SDR) CONNAME('coordination-ibm-mq(1414)') XMITQ(COORD) CONVERT(NO)
    DEFINE QLOCAL(COMMAND) USAGE(XMITQ)
    DEFINE CHANNEL(AGENT.DEST.COMMAND) CHLTYPE(SDR) CONNAME('command-ibm-mq(1414)') XMITQ(COORD) CONVERT(NO)
    DEFINE QLOCAL(AGENT.SOURCE) USAGE(XMITQ)
    DEFINE CHANNEL(AGENT.DEST.SOURCE) CHLTYPE(SDR) CONNAME('agent-source-ibm-mq(1414)') XMITQ(COORD) CONVERT(NO)
    DEFINE CHANNEL(COMMAND.AGENT.DEST) CHLTYPE(RCVR)
    DEFINE CHANNEL(AGENT.SOURCE.DEST) CHLTYPE(RCVR)
